name: 'Auto Changelog and Save as file'
description: 'Automatic Changelog generator'
author: 'AXIM0S'
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  token:
    description: 'Github token'
    required: true
  exclude:
    description: 'Exclude selected commit types (comma separated)'
    required: false
    default: ''
outputs:
  changelog:
    description: 'The generated changelogs'
runs:
  using: 'node12'
  main: 'action/index.js'
